### ISSUE TITLE
controlBoardWrapper2 compilation error

### ISSUE THREAD

**Issue by gsaponaro** [robotology/icub-main#41]
I encountered this error while compiling the icub-main build on Ubuntu 12.04, g++ 4.6.3, yarp 2.3.63. See also robotology/yarp#203

```
[ 32%] Building CXX object src/libraries/icubmod/controlBoardWrapper2/CMakeFiles/controlboardwrapper2.dir/__/__/__/__/generated_code/yarpdev_add_controlboardwrapper2.cpp.o
In file included from /home/gsaponaro/NOBACKUP/icub-main/build/generated_code/yarpdev_add_controlboardwrapper2.cpp:21:0:
/home/gsaponaro/NOBACKUP/icub-main/src/libraries/icubmod/controlBoardWrapper2/ControlBoardWrapper2.h: In member function ‘virtual bool ControlBoardWrapper2::setOutput(int, double)’:
/home/gsaponaro/NOBACKUP/icub-main/src/libraries/icubmod/controlBoardWrapper2/ControlBoardWrapper2.h:3659:34: error: ‘class yarp::dev::IOpenLoopControl’ has no member named ‘setOutput’
/home/gsaponaro/NOBACKUP/icub-main/src/libraries/icubmod/controlBoardWrapper2/ControlBoardWrapper2.h: In member function ‘virtual bool ControlBoardWrapper2::setOutputs(const double*)’:
/home/gsaponaro/NOBACKUP/icub-main/src/libraries/icubmod/controlBoardWrapper2/ControlBoardWrapper2.h:3678:40: error: ‘class yarp::dev::IOpenLoopControl’ has no member named ‘setOutput’
/home/gsaponaro/NOBACKUP/icub-main/build/generated_code/yarpdev_add_controlboardwrapper2.cpp: In function ‘void* controlboardwrapper2_create()’:
/home/gsaponaro/NOBACKUP/icub-main/build/generated_code/yarpdev_add_controlboardwrapper2.cpp:40:1: error: cannot allocate an object of abstract type ‘ControlBoardWrapper2’
/home/gsaponaro/NOBACKUP/icub-main/src/libraries/icubmod/controlBoardWrapper2/ControlBoardWrapper2.h:256:7: note:   because the following virtual functions are pure within ‘ControlBoardWrapper2’:
/home/gsaponaro/NOBACKUP/yarp/src/libYARP_dev/include/yarp/dev/IPositionDirect.h:50:18: note:   virtual bool yarp::dev::IPositionDirect::setPositionDirectMode()
/home/gsaponaro/NOBACKUP/yarp/src/libYARP_dev/include/yarp/dev/IOpenLoopControl.h:89:18: note:  virtual bool yarp::dev::IOpenLoopControl::setRefOutput(int, double)
/home/gsaponaro/NOBACKUP/yarp/src/libYARP_dev/include/yarp/dev/IOpenLoopControl.h:94:18: note:  virtual bool yarp::dev::IOpenLoopControl::setRefOutputs(const double*)
/home/gsaponaro/NOBACKUP/yarp/src/libYARP_dev/include/yarp/dev/IOpenLoopControl.h:102:18: note:     virtual bool yarp::dev::IOpenLoopControl::getRefOutput(int, double*)
/home/gsaponaro/NOBACKUP/yarp/src/libYARP_dev/include/yarp/dev/IOpenLoopControl.h:109:18: note:     virtual bool yarp::dev::IOpenLoopControl::getRefOutputs(double*)
In file included from /home/gsaponaro/NOBACKUP/icub-main/build/generated_code/yarpdev_add_controlboardwrapper2.cpp:10:0:
/home/gsaponaro/NOBACKUP/yarp/src/libYARP_dev/include/yarp/dev/Drivers.h: In member function ‘yarp::dev::DeviceDriver* yarp::dev::DriverCreatorOf<T>::create() [with T = ControlBoardWrapper2]’:
/home/gsaponaro/NOBACKUP/icub-main/build/generated_code/yarpdev_add_controlboardwrapper2.cpp:40:1:   instantiated from here
/home/gsaponaro/NOBACKUP/yarp/src/libYARP_dev/include/yarp/dev/Drivers.h:127:20: error: cannot allocate an object of abstract type ‘ControlBoardWrapper2’
/home/gsaponaro/NOBACKUP/icub-main/src/libraries/icubmod/controlBoardWrapper2/ControlBoardWrapper2.h:256:7: note:   since type ‘ControlBoardWrapper2’ has pure virtual functions
make[2]: *** [src/libraries/icubmod/controlBoardWrapper2/CMakeFiles/controlboardwrapper2.dir/__/__/__/__/generated_code/yarpdev_add_controlboardwrapper2.cpp.o] Error 1
make[1]: *** [src/libraries/icubmod/controlBoardWrapper2/CMakeFiles/controlboardwrapper2.dir/all] Error 2
make: *** [all] Error 2
```
