### PR TITLE
Port embObjSkin and iCubSkinGui to yarp 4

### PR DESCRIPTION
**Pull request by MSECode**
Migrate embObjSkin to ISkinPatches
Tested skinPaches on setup
Udpdate methods and enums for embObjSkin
Finalize the update for iCubSkinGui

### CODE REVIEW

**Comment by MSECode** [comment]
Keep PR on draft until test on an icub robot or a multiple ETH boards skin setup

**Comment by valegagge** [comment]
> Keep PR on draft until test on an icub robot or a multiple ETH boards skin setup

Unfortunately, we hadn't the chance to test on multiple eth boards.
In any case, we can proceed to merge this and test this use case later.

cc @MSECode

**Comment by valegagge** [comment]
## Code review changes applied to embObjSkin (commit https://github.com/MSECode/icub-main/commit/afcfb3aef991a60f72a42ac1495c2e14a08cbeb1 )

The following improvements have been applied to `embObjSkin.cpp/.h`:

### Bug fixes
- **Memory leak**: `boardCfgList` was allocated with `new[]` but never
  `delete[]`'d, especially on early `return false` paths. Replaced with
  `std::vector<>`. Same for the stack array `triangleCfg[SPECIAL_TRIANGLE_CFG_MAX_NUM]`.
  The compiler-generated destructors now guarantee cleanup on every exit path.

### API safety improvement
- `checkCardAddrIsInList()` previously returned `int` with `-1` as a
  sentinel value, which is a C-style pattern that allows silent misuse
  (e.g. using the value as an index without checking). Changed return type
  to `std::optional<size_t>`: the compiler now forces callers to check for
  absence before accessing the value.

### Logging consistency
- Added `boardInfo()` private helper method that returns a formatted string
  `"BOARD <name> IP <addr>"` (with a null-guard for early calls before `res`
  is assigned). This replaces ~20 repetitions of
  `res->getProperties().boardnameString << "IP" << res->getProperties().ipv4addrString`
  scattered across all log messages.
- Replaced all hardcoded function name strings (e.g. `"initWithSpecialConfig():"`,
  `"fromConfig():"`) in log messages with the `__YFUNCTION__` macro, so
  function names in logs are always accurate even after refactoring.
- Fixed log component name casing: `"yarp.dev.embObjSKIN"` → `"yarp.dev.embObjSkin"`.

### Minor cleanups
- Moved `isCANaddressValid()` into the anonymous namespace (already present
  for `YARP_LOG_COMPONENT` and `defaultSkinNoLoadValue`) to enforce
  translation-unit-local linkage and avoid ODR conflicts.
- Removed unused local variables `bNumOfset` and `numOfSets` in
  `initWithSpecialConfig()`.
- Fixed typo `"propertiex"` → `"properties"` in one error message in `open()`.


I'm sorry but, I couldn't compile 😢

**Comment by MSECode** [comment]
Hi @valegagge,
I checked the modifications and re-compiled. I have a couple of points here:
- since I'm not aware of all the updates done in YARP I need to notify that, after rebasing everything on the `yarp4` branch, I needed to exclude from the compiling tools and models otherwise the build would fail
- I removed the auto initialization of `p` and `j` in `bool EmbObjSkin::initWithSpecialConfig(yarp::os::Searchable& config)` since they are re-used outside of the for loop, thus they need to be initialized as `unsigned int` at the beginning of the method

I've just tested that icub-main build correctly (with the exclusion said above)

**Comment by valegagge** [comment]
Ok! Thanks @MSECode !
My changes were just a moment to recall some new feature of modern c++ and improve the code readability. 

Regarding point 1, I didn't understand what we had to remove from compilation .

Thanks

**Comment by MSECode** [comment]
Hi @valegagge 
Yes sure and they were all good and helpful.
I just need to make that modification for the for loop indexes in order to make the code compiling (auto would be better but those indexes are used elsewhere in the method)
For point 1 I need to set the cmake option `ICUBMAIN_COMPILE_TOOLS` and `ICUBMAIN_COMPILE_MODELS` to OFF.
I got a compilation failure for something related to the cameras (I'll upload here the exact error)

This is the error in the build: I suppose is due to `openCV` dependencies, thus do you know if there is some braking change with version older than a specific one?:
```
[ 74%] Building CXX object src/modules/cartesianInterfaceControl/CMakeFiles/cartesianInterfaceControl.dir/main.cpp.o
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/modules/motionCUT/main.cpp: In member function ‘virtual void ProcessThread::run()’:
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/modules/motionCUT/main.cpp:225:67: error: ‘CV_BGR2GRAY’ was not declared in this scope
  225 |                 cvtColor(toCvMat(*pImgBgrIn),toCvMat(imgMonoPrev),CV_BGR2GRAY);
      |                                                                   ^~~~~~~~~~~
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/modules/motionCUT/main.cpp:239:61: error: ‘CV_BGR2GRAY’ was not declared in this scope
  239 |             cvtColor(toCvMat(*pImgBgrIn),toCvMat(imgMonoIn),CV_BGR2GRAY);
      |                                                             ^~~~~~~~~~~
make[2]: *** [src/modules/motionCUT/CMakeFiles/motionCUT.dir/build.make:76: src/modules/motionCUT/CMakeFiles/motionCUT.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4952: src/modules/motionCUT/CMakeFiles/motionCUT.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 74%] Building CXX object src/libraries/icubmod/rawValuesPublisherClient/CMakeFiles/rawValuesPublisherClient.dir/RawValuesPublisherClient_ParamsParser.cpp.o
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::stereoCalibRun()’:
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:195:44: error: ‘CV_RGB2BGR’ was not declared in this scope; did you mean ‘CV_RGB’?
  195 |                         cvtColor(Left,Left,CV_RGB2BGR);
      |                                            ^~~~~~~~~~
      |                                            CV_RGB
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::monoCalibRun()’:
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:316:44: error: ‘CV_RGB2BGR’ was not declared in this scope; did you mean ‘CV_RGB’?
  316 |                         cvtColor(Left,Left,CV_RGB2BGR);
      |                                            ^~~~~~~~~~
      |                                            CV_RGB
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp: In member function ‘void stereoCalibThread::monoCalibration(const std::vector<std::__cxx11::basic_string<char> >&, int, int, cv::Mat&, cv::Mat&)’:
/home/jlosi/Workspace/robotology-superbuild/src/ICUB/src/tools/stereoCalib/src/stereoCalibThread.cpp:619:35: error: ‘CV_BGR2GRAY’ was not declared in this scope
  619 |          cvtColor(view, viewGray, CV_BGR2GRAY);
      |                                   ^~~~~~~~~~~
make[2]: *** [src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/build.make:104: src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/src/stereoCalibThread.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4447: src/tools/stereoCalib/CMakeFiles/stereoCalib.dir/all] Error 2
[ 74%] Linking CXX executable ../../../bin/cartesianInterfaceControl
[ 74%] Built target cartesianInterfaceControl
[ 74%] Linking CXX shared module ../../../../lib/yarp/rawValuesPublisherClient.so
[ 74%] Built target rawValuesPublisherClient
make: *** [Makefile:146: all] Error 2
```

**Comment by valegagge** [comment]
Thanks @MSECode ! Now I undestand!

I didn't face the compiling issue with the icub-main tools. Which version of OpenCV have you installed?

**Comment by MSECode** [comment]
> Thanks @MSECode ! Now I undestand!
> 
> I didn't face the compiling issue with the icub-main tools. Which version of OpenCV have you installed?

I'll  check. Moreover, I'll run a fresh build in the yri on a sandboxed env (such as docker) since lately I'm working on both yarp4 and yarp 3.12, thus it might be I have dependencies problems
I've run the compilation under a docker container thus I had a clean env.
I still get this error when building icub-main modules:
```
[ 51%] Building CXX object src/modules/dualCamCalib/CMakeFiles/dualCamCalib.dir/src/PinholeCalibTool.cpp.o
/projects/robotology-superbuild/src/ICUB/src/modules/motionCUT/main.cpp: In member function 'virtual void ProcessThread::run()':
/projects/robotology-superbuild/src/ICUB/src/modules/motionCUT/main.cpp:225:67: error: 'CV_BGR2GRAY' was not declared in this scope
  225 |                 cvtColor(toCvMat(*pImgBgrIn),toCvMat(imgMonoPrev),CV_BGR2GRAY);
      |                                                                   ^~~~~~~~~~~
/projects/robotology-superbuild/src/ICUB/src/modules/motionCUT/main.cpp:239:61: error: 'CV_BGR2GRAY' was not declared in this scope
  239 |             cvtColor(toCvMat(*pImgBgrIn),toCvMat(imgMonoIn),CV_BGR2GRAY);
      |                                                             ^~~~~~~~~~~
```

OpenCV version: `4.5.4`

**Comment by valegagge** [comment]
Hi @MSECode ,
Thanks for pointing out the compilation issue. I fixed it in [4840f97](https://github.com/robotology/icub-main/pull/1063/commits/4840f972daae94c19ee77d87cda827616e47b5d8)

The build failure is caused by the use of `CV_BGR2GRAY`, a legacy C-style macro 
deprecated since OpenCV 3 and not guaranteed to be available in all OpenCV 4 builds.

Depending on how OpenCV was installed (e.g. from source vs. system package), the 
legacy header `opencv2/imgproc/types_c.h` — which defines these `CV_*` constants — 
may or may not be pulled in transitively. This explains why the code compiled on one 
machine but not the other, despite both running OpenCV 4.5.4.

The fix is to replace `CV_BGR2GRAY` with the modern `COLOR_BGR2GRAY` enum value from 
`cv::ColorConversionCodes`, which is always available in OpenCV 3+/4.x regardless of 
the installation method.

The change has been applied in `src/modules/motionCUT/main.cpp` (two occurrences).

If for you these changes are fine, we can merge the PR, but before I suggest squashing them.

>[!IMPORTANT]
>  ⚠️ I did a commit on yarp4 branch so I needed to rebase your branch. 
>  ⚠️ You need also to pull the last commit of `icub-firmware-shared/yarp4` to make your branch working

**Comment by MSECode** [comment]
Hi @valegagge,
Oks, I'll test it. For the squash you can do it from here while merging.
I needed to update other files in `tools` and `modules`: d2465496a7a7c142f6072160b0b1ddaf1047d954
You can review the latest commit. The build completes successfully now. You can squash and merge here.

**Comment by valegagge** [comment]
Hi @MSECode ,
thanks!

> For the squash you can do it from here while merging.

yes, I know, but I think it is better to have two separate commits. One for the opencv update and the other to the porting. Thanks!

**Review by valegagge — APPROVED** [review]
Thanks @MSECode!
